import Foundation
import XCTest

/// Loads recorded provider payloads from `Tests/RacesKitTests/Fixtures/`.
///
/// `Bundle.module` is generated by SwiftPM and works identically on Linux and
/// macOS, which is what lets the fixture-driven tests be the Linux job's main job.
enum Fixture {

    enum Error: Swift.Error, CustomStringConvertible {
        case missing(String)

        var description: String {
            switch self {
            case .missing(let name):
                return "Fixture '\(name)' not found. Add it under Tests/RacesKitTests/Fixtures/."
            }
        }
    }

    /// Raw bytes of a fixture file. `name` includes the extension, e.g. `"courses.json"`.
    static func data(_ name: String) throws -> Data {
        guard let url = Bundle.module.url(forResource: "Fixtures/\(name)", withExtension: nil)
            ?? Bundle.module.url(forResource: name, withExtension: nil) else {
            throw Error.missing(name)
        }
        return try Data(contentsOf: url)
    }

    static func string(_ name: String) throws -> String {
        String(decoding: try data(name), as: UTF8.self)
    }

    /// Decode a fixture directly into a model, so a fixture that drifts from the
    /// model fails loudly in CI rather than silently producing empty results.
    static func decode<T: Decodable>(
        _ type: T.Type = T.self,
        from name: String,
        using decoder: JSONDecoder = JSONDecoder()
    ) throws -> T {
        try decoder.decode(type, from: try data(name))
    }
}
