import Foundation
import XCTest

/// Loads recorded provider payloads from `Tests/RacesKitTests/Fixtures/`.
///
/// `Bundle.module` is generated by SwiftPM and behaves identically on Linux and
/// macOS, which is what lets fixture-driven tests be the Linux job's main job.
enum Fixture {

    enum Error: Swift.Error, CustomStringConvertible {
        case missing(String)

        var description: String {
            switch self {
            case .missing(let name):
                return "Fixture '\(name)' not found. Add it under Tests/RacesKitTests/Fixtures/."
            }
        }
    }

    /// Raw bytes of a fixture file. `name` includes the extension.
    ///
    /// Tries the `Fixtures` subdirectory first, since `.copy` preserves the
    /// directory, then the bundle root, since `.process` would flatten it. Being
    /// tolerant of both means changing the resource rule in `Package.swift` never
    /// silently breaks every fixture test at once.
    static func data(_ name: String) throws -> Data {
        let candidates: [URL?] = [
            Bundle.module.url(forResource: name, withExtension: nil, subdirectory: "Fixtures"),
            Bundle.module.url(forResource: name, withExtension: nil),
            Bundle.module.resourceURL?.appendingPathComponent("Fixtures").appendingPathComponent(name),
        ]
        for case let url? in candidates where FileManager.default.fileExists(atPath: url.path) {
            return try Data(contentsOf: url)
        }
        throw Error.missing(name)
    }

    static func string(_ name: String) throws -> String {
        String(decoding: try data(name), as: UTF8.self)
    }

    /// Decode a fixture straight into a model, so a fixture that drifts from the
    /// model fails loudly in CI rather than quietly producing empty results.
    static func decode<T: Decodable>(
        _ type: T.Type = T.self,
        from name: String,
        using decoder: JSONDecoder = JSONDecoder()
    ) throws -> T {
        try decoder.decode(type, from: try data(name))
    }
}

/// Sanity check on the loader itself. If this fails every other fixture test is
/// failing for the same uninteresting reason.
final class FixtureLoadingTests: XCTestCase {
    func test_fixturesAreReachableFromTheTestBundle() throws {
        for name in [
            "racingapi-courses.json",
            "racingapi-racecards-free.json",
            "racingapi-results-today-free.json",
        ] {
            let data = try Fixture.data(name)
            XCTAssertFalse(data.isEmpty, "\(name) is empty")
        }
    }
}
